version: '3.8'

services:
  mysql-master:
    image: mysql:latest
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=testdb
    volumes:
      - mysql_master_data:/var/lib/mysql

  mysql-slave:
    image: mysql:latest
    container_name: mysql-slave
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mysql-master
    ports:
      - "3308:3306"
    command: --server-id=2 --relay-log=mysql-relay-bin --read-only=1
    volumes:
      - mysql_slave_data:/var/lib/mysql

volumes:
  mysql_master_data:
  mysql_slave_data: